default:
  app:
    name: Recurring Payments API
    version: 0.1.0

  broker:
    amqp:
      exchange: "recurring-payments"
      username:
      password:
      host: localhost:5672
      port:
      topics: ["mandates.commands"]
      queue: recurring.payments.api.0.1.0
      queueOptions:
        exclusive: false
        durable: true
        autoDelete: true

development:

test:

staging:

production:
